/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/n8PxBcPbryx
 */
import * as React from 'react';
import { NavLink } from 'react-router-dom';
import { cn } from '@/lib/utils';

export type NavbarRouteProps = {
  name: string;
  path: string;
};

type NavbarProps = {
  className?: string;
  routes: NavbarRouteProps[];
};

export default function Navbar({ routes, className }: NavbarProps) {
  return (
    <header className={cn('flex h-16 w-full items-center justify-between border-b px-4', className)}>
      <nav className="flex items-center gap-8">
        <ul>
          {routes.map((route) => (
            <li key={route.name}>
              <NavLink
                to={route.path}
                className={({ isActive, isPending }) =>
                  isPending
                    ? 'font-bold text-purple-500'
                    : isActive
                      ? 'font-bold text-red-500'
                      : 'font-bold text-green-500'
                }
              >
                {route.name}
              </NavLink>
            </li>
          ))}
        </ul>
      </nav>
    </header>
  );
}
